# This is a basic workflow to help you get started with Actions

name: release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ deploy ]
  repository_dispatch:
    type: [ build ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
      with:
        ref: 'deploy'

    # Runs a single command using the runners shell
    - name: Configration on Ubuntu 18.04
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Deploy configration
      run: |
          mkdir ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          
    - name: Build
      run: |
          yarn install
          yarn export
          
    - name: Push to GitHub
      env:
        GITHUB_USER: "imtkzk"
        GITHUB_EMAIL: "info@cullumdesign.com"
      run: |
          git config --local user.name "${GITHUB_USER}"
          git config --local user.email "${GITHUB_EMAIL}"
          git remote set-url origin git@github.com:imtkzk/imoto_day4.git
          git add -f docs
          git add .
          git commit -m "auto rebuilding site"
          git push -f origin HEAD:master
